sonar.projectKey=foodgorilla
sonar.projectName=Food Gorilla
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/.pytest_cache/**
sonar.python.version=3.10
sonar.sourceEncoding=UTF-8
